mutation addWork($input: addWorkInput!) {
  addWork(input: $input) {
    id
    title
    description
    thumbnail {
      key
      url
    }
    tags
    published
    category {
      id
      name
    }
  }
}
